spring:
  jpa:
    show-sql: true
  flyway:
    enabled: true

app:
  dev-mode: true

logging:
  level:
    com.localpro: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
